version: '3.8'

services:
  es:
    image: elastic/elasticsearch:7.17.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  kibana:
    image: elastic/kibana:7.17.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
      - ELASTICSEARCH_USERNAME=kibana_system
    depends_on:
      - es

  db:
    image: "mongodb/mongodb-community-server"
    ports:
      - "27017:27017"

  web:
    build: .
    command: python ./manage.py runserver
    ports:
      - "8000:8000"
    env_file:
      - docker-compose.env
    depends_on:
      - db
      - es